theme: jekyll-theme-cayman
title: "Structure and Empathy in Visual Data Storytelling:<br /> Evaluating their Influence on Attitude"
description: "Johannes Liem, Charles Perin, Jo Wood"
show_downloads: true